<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

$vardefs = array (
  'fields' => 
  array (
    'date_prepared' => 
    array (
      'required' => false,
      'name' => 'date_prepared',
      'vname' => 'LBL_DATE_PREPARED',
      'type' => 'date',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
    ),
    'name' => 
    array (
      'name' => 'name',
      'vname' => 'LBL_NAME',
      'type' => 'name',
      'link' => true,
      'dbType' => 'varchar',
      'len' => '255',
      'unified_search' => false,
      'full_text_search' => 
      array (
        'boost' => 3,
      ),
      'required' => true,
      'importable' => 'required',
      'duplicate_merge' => 'disabled',
      'merge_filter' => 'disabled',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'size' => '20',
    ),
    'department_name' => 
    array (
      'required' => false,
      'name' => 'department_name',
      'vname' => 'LBL_DEPARTMENT_NAME',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
    ),
    'executive_summary' => 
    array (
      'required' => false,
      'source' => 'non-db',
      'name' => 'executive_summary',
      'vname' => 'LBL_EXECUTIVE_SUMMARY',
      'type' => 'html',
      'massupdate' => 0,
      'default' => '&lt;h1&gt;Executive Summary&lt;/h1&gt;
&lt;p&gt;&lt;strong&gt;This section should provide general information on the issues surrounding the business problem and the proposed project or initiative created to address it. Usually, this section is completed last after all other sections of the business case have been written. This is because the executive summary is exactly that, a summary of the detail that is provided in subsequent sections of the document.&lt;/strong&gt;&lt;/p&gt;',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'default_value' => '&lt;h1&gt;Executive Summary&lt;/h1&gt;
&lt;p&gt;&lt;strong&gt;This section should provide general information on the issues surrounding the business problem and the proposed project or initiative created to address it. Usually, this section is completed last after all other sections of the business case have been written. This is because the executive summary is exactly that, a summary of the detail that is provided in subsequent sections of the document.&lt;/strong&gt;&lt;/p&gt;',
      'studio' => 'visible',
      'dbType' => 'text',
    ),
    'description' => 
    array (
      'name' => 'description',
      'vname' => 'LBL_DESCRIPTION',
      'type' => 'text',
      'comment' => 'Full text of the note',
      'rows' => '6',
      'cols' => '80',
      'required' => false,
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Full text of the note',
      'help' => 'What is the problem that the project will address.',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
    ),
    'anticipated_outcomes' => 
    array (
      'required' => false,
      'name' => 'anticipated_outcomes',
      'vname' => 'LBL_ANTICIPATED_OUTCOMES',
      'type' => 'text',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => 'How will project benefit organization; summary of financial impact; summary of timeline',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '6',
      'cols' => '80',
    ),
    'recomendation' => 
    array (
      'required' => false,
      'name' => 'recomendation',
      'vname' => 'LBL_RECOMENDATION',
      'type' => 'text',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => 'How will approach address problem; how will results be achieved',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '6',
      'cols' => '80',
    ),
    'justification' => 
    array (
      'required' => false,
      'name' => 'justification',
      'vname' => 'LBL_JUSTIFICATION',
      'type' => 'text',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => 'Why this alternative was selected over others and impact if project is not implemented',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '6',
      'cols' => '80',
    ),
    'project_overview' => 
    array (
      'required' => false,
      'source' => 'non-db',
      'name' => 'project_overview',
      'vname' => 'LBL_PROJECT_OVERVIEW',
      'type' => 'html',
      'massupdate' => 0,
      'default' => '&lt;h1&gt;Project Overview&lt;/h1&gt;
&lt;p&gt;&lt;strong&gt;This section describes high-level information about the project to include a description, goals and objectives, performance criteria, assumptions, constraints, and milestones. &nbsp;This section consolidates all project-specific information into one chapter and allows for an easy understanding of the project since the baseline business problem, impacts, and recommendations have already been established.&lt;/strong&gt;&lt;/p&gt;',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'default_value' => '&lt;h1&gt;Project Overview&lt;/h1&gt;
&lt;p&gt;&lt;strong&gt;This section describes high-level information about the project to include a description, goals and objectives, performance criteria, assumptions, constraints, and milestones. &nbsp;This section consolidates all project-specific information into one chapter and allows for an easy understanding of the project since the baseline business problem, impacts, and recommendations have already been established.&lt;/strong&gt;&lt;/p&gt;',
      'studio' => 'visible',
      'dbType' => 'text',
    ),
    'current_situation' => 
    array (
      'required' => false,
      'name' => 'current_situation',
      'vname' => 'LBL_CURRENT_SITUATION',
      'type' => 'text',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'The problem may be process, technology, or product/service oriented',
      'help' => 'The problem may be process, technology, or product/service oriented',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '6',
      'cols' => '80',
    ),
    'project_description' => 
    array (
      'required' => false,
      'name' => 'project_description',
      'vname' => 'LBL_PROJECT_DESCRIPTION ',
      'type' => 'text',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => 'The approach the project will use to address problem',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '6',
      'cols' => '80',
    ),
    'project_assumptions' => 
    array (
      'required' => false,
      'name' => 'project_assumptions',
      'vname' => 'LBL_PROJECT_ASSUMPTIONS ',
      'type' => 'text',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => 'List initial assumptions',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '6',
      'cols' => '80',
    ),
    'project_constraints' => 
    array (
      'required' => false,
      'name' => 'project_constraints',
      'vname' => 'LBL_PROJECT_CONSTRAINTS ',
      'type' => 'text',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => 'Preliminary constraints on project (i.e. resources, time, etc.)',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '6',
      'cols' => '80',
    ),
    'major_project_milestones' => 
    array (
      'required' => false,
      'name' => 'major_project_milestones',
      'vname' => 'LBL_MAJOR_PROJECT_MILESTONES',
      'type' => 'text',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '1.8	General milestones and target completion dates',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '6',
      'cols' => '80',
    ),
    'project_roll_over' => 
    array (
      'required' => false,
      'name' => 'project_roll_over',
      'vname' => 'LBL_PROJECT_ROLL_OVER',
      'type' => 'radioenum',
      'massupdate' => 0,
      'default' => 'yes',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'Selkirk_Yes_No',
      'studio' => 'visible',
      'dbType' => 'enum',
      'separator' => '<br>',
    ),
    'strategic_alignment_hdr' => 
    array (
      'required' => false,
      'source' => 'non-db',
      'name' => 'strategic_alignment_hdr',
      'vname' => 'LBL_STRATEGIC_ALIGNMENT_HDR',
      'type' => 'html',
      'massupdate' => 0,
      'default' => '&lt;h1&gt;Strategic Alignment&lt;/h1&gt;
&lt;p&gt;&lt;strong&gt;All projects should support the organization&rsquo;s strategy and strategic plans in order to add value and maintain executive and organizational support. &nbsp;This section provides an overview of the organizational strategic plans that are related to the project. &nbsp;This includes the strategic plan, what the plan calls for, and how the project supports the strategic plan.&lt;/strong&gt;&lt;/p&gt;',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'default_value' => '&lt;h1&gt;Strategic Alignment&lt;/h1&gt;
&lt;p&gt;&lt;strong&gt;All projects should support the organization&rsquo;s strategy and strategic plans in order to add value and maintain executive and organizational support. &nbsp;This section provides an overview of the organizational strategic plans that are related to the project. &nbsp;This includes the strategic plan, what the plan calls for, and how the project supports the strategic plan.&lt;/strong&gt;&lt;/p&gt;',
      'studio' => 'visible',
      'dbType' => 'text',
    ),
    'strategic_alignment' => 
    array (
      'required' => false,
      'name' => 'strategic_alignment',
      'vname' => 'LBL_STRATEGIC_ALIGNMENT',
      'type' => 'text',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '6',
      'cols' => '80',
    ),
    'cost_benefit_analysis_hdr' => 
    array (
      'required' => false,
      'source' => 'non-db',
      'name' => 'cost_benefit_analysis_hdr',
      'vname' => 'LBL_COST_BENEFIT_ANALYSIS_HDR',
      'type' => 'html',
      'massupdate' => 0,
      'default' => '&lt;h1&gt;Cost/Benefit Analysis&lt;/h1&gt;
&lt;p&gt;&lt;strong&gt;Information that quantifies the financial benefits of the project as much as possible in the business case. Illustrate the costs of the project and compare them with the benefits and savings to determine if the project is worth pursuing.&lt;/strong&gt;&lt;/p&gt;',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'default_value' => '&lt;h1&gt;Cost/Benefit Analysis&lt;/h1&gt;
&lt;p&gt;&lt;strong&gt;Information that quantifies the financial benefits of the project as much as possible in the business case. Illustrate the costs of the project and compare them with the benefits and savings to determine if the project is worth pursuing.&lt;/strong&gt;&lt;/p&gt;',
      'studio' => 'visible',
      'dbType' => 'text',
    ),
    'tangible_intangible_benefits' => 
    array (
      'required' => false,
      'source' => 'non-db',
      'name' => 'tangible_intangible_benefits',
      'vname' => 'LBL_TANGIBLE_INTANGIBLE_BENEFITS',
      'type' => 'html',
      'massupdate' => 0,
      'default' => '&lt;h2&gt;Tangible &nbsp;&amp; Intangible Benefits&lt;/h2&gt;',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'default_value' => '&lt;h2&gt;Tangible &nbsp;&amp; Intangible Benefits&lt;/h2&gt;',
      'studio' => 'visible',
      'dbType' => 'text',
    ),
    'community_profile' => 
    array (
      'required' => false,
      'name' => 'community_profile',
      'vname' => 'LBL_COMMUNITY_PROFILE',
      'type' => 'text',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '6',
      'cols' => '80',
    ),
    'tangible_intangible_cost' => 
    array (
      'required' => false,
      'source' => 'non-db',
      'name' => 'tangible_intangible_cost',
      'vname' => 'LBL_TANGIBLE_INTANGIBLE_COST',
      'type' => 'html',
      'massupdate' => 0,
      'default' => '&lt;h2&gt;Tangible &amp; Intangible Costs&lt;/h2&gt;',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'default_value' => '&lt;h2&gt;Tangible &amp; Intangible Costs&lt;/h2&gt;',
      'studio' => 'visible',
      'dbType' => 'text',
    ),
    'new_revenues' => 
    array (
      'required' => false,
      'name' => 'new_revenues',
      'vname' => 'LBL_NEW_REVENUES',
      'type' => 'text',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '6',
      'cols' => '80',
    ),
    'labour_material' => 
    array (
      'required' => false,
      'name' => 'labour_material',
      'vname' => 'LBL_LABOUR_MATERIAL',
      'type' => 'text',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '6',
      'cols' => '80',
    ),
    'job_impact_productivity_loss' => 
    array (
      'required' => false,
      'name' => 'job_impact_productivity_loss',
      'vname' => 'LBL_JOB_IMPACT_PRODUCTIVITY_LOSS',
      'type' => 'text',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '6',
      'cols' => '80',
    ),
    'overall_revenue_cost_project' => 
    array (
      'required' => false,
      'name' => 'overall_revenue_cost_project',
      'vname' => 'LBL_OVERALL_REVENUE_COST_PROJECT',
      'type' => 'text',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '6',
      'cols' => '80',
    ),
    'cashflow_projects' => 
    array (
      'required' => false,
      'name' => 'cashflow_projects',
      'vname' => 'LBL_CASHFLOW_PROJECTS',
      'type' => 'text',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '6',
      'cols' => '80',
    ),
    'pay_back_return_on_investment' => 
    array (
      'required' => false,
      'name' => 'pay_back_return_on_investment',
      'vname' => 'LBL_PAY_BACK_RETURN_ON_INVESTMENT',
      'type' => 'text',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '6',
      'cols' => '80',
    ),
    'alternative_analysis_hrd' => 
    array (
      'required' => false,
      'source' => 'non-db',
      'name' => 'alternative_analysis_hrd',
      'vname' => 'LBL_ALTERNATIVE_ANALYSIS_HRD',
      'type' => 'html',
      'massupdate' => 0,
      'default' => '&lt;h1&gt;Alternative Analysis&lt;/h1&gt;
&lt;p&gt;&lt;strong&gt;All business problems may be addressed by any number of alternative projects. &nbsp;Include a brief summary of considered alternatives including status quo or doing nothing. &nbsp;Also include reasons for not selecting alternatives.&lt;/strong&gt;&lt;/p&gt;',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'default_value' => '&lt;h1&gt;Alternative Analysis&lt;/h1&gt;
&lt;p&gt;&lt;strong&gt;All business problems may be addressed by any number of alternative projects. &nbsp;Include a brief summary of considered alternatives including status quo or doing nothing. &nbsp;Also include reasons for not selecting alternatives.&lt;/strong&gt;&lt;/p&gt;',
      'studio' => 'visible',
      'dbType' => 'text',
    ),
    'alternative_analysis' => 
    array (
      'required' => false,
      'name' => 'alternative_analysis',
      'vname' => 'LBL_ALTERNATIVE_ANALYSIS',
      'type' => 'text',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '6',
      'cols' => '80',
    ),
    'risks' => 
    array (
      'required' => false,
      'name' => 'risks',
      'vname' => 'LBL_RISKS',
      'type' => 'text',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '6',
      'cols' => '80',
    ),
    'future_development' => 
    array (
      'required' => false,
      'name' => 'future_development',
      'vname' => 'LBL_FUTURE_DEVELOPMENT',
      'type' => 'text',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '6',
      'cols' => '80',
    ),
  ),
  'relationships' => 
  array (
  ),
);