<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'sel',
  'author' => '',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Selkirk',
  'published_date' => '2014-09-02 21:30:38',
  'type' => 'module',
  'version' => 1409693439,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Selkirk',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'sel_Selkirk_Activity',
      'class' => 'sel_Selkirk_Activity',
      'path' => 'modules/sel_Selkirk_Activity/sel_Selkirk_Activity.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'sel_Selkirk_Service',
      'class' => 'sel_Selkirk_Service',
      'path' => 'modules/sel_Selkirk_Service/sel_Selkirk_Service.php',
      'tab' => true,
    ),
    2 => 
    array (
      'module' => 'sel_Selkirk_Funding',
      'class' => 'sel_Selkirk_Funding',
      'path' => 'modules/sel_Selkirk_Funding/sel_Selkirk_Funding.php',
      'tab' => true,
    ),
    3 => 
    array (
      'module' => 'sel_Selkirk_Template',
      'class' => 'sel_Selkirk_Template',
      'path' => 'modules/sel_Selkirk_Template/sel_Selkirk_Template.php',
      'tab' => true,
    ),
    4 => 
    array (
      'module' => 'sel_Selkirk_Contact',
      'class' => 'sel_Selkirk_Contact',
      'path' => 'modules/sel_Selkirk_Contact/sel_Selkirk_Contact.php',
      'tab' => true,
    ),
    5 => 
    array (
      'module' => 'sel_Student_Activity',
      'class' => 'sel_Student_Activity',
      'path' => 'modules/sel_Student_Activity/sel_Student_Activity.php',
      'tab' => true,
    ),
    6 => 
    array (
      'module' => 'sel_Selkirk_Team',
      'class' => 'sel_Selkirk_Team',
      'path' => 'modules/sel_Selkirk_Team/sel_Selkirk_Team.php',
      'tab' => true,
    ),
    7 => 
    array (
      'module' => 'sel_Selkirk_Document',
      'class' => 'sel_Selkirk_Document',
      'path' => 'modules/sel_Selkirk_Document/sel_Selkirk_Document.php',
      'tab' => true,
    ),
    8 => 
    array (
      'module' => 'sel_Selkirk_Project',
      'class' => 'sel_Selkirk_Project',
      'path' => 'modules/sel_Selkirk_Project/sel_Selkirk_Project.php',
      'tab' => true,
    ),
    9 => 
    array (
      'module' => 'sel_Selkirk_Business_Case',
      'class' => 'sel_Selkirk_Business_Case',
      'path' => 'modules/sel_Selkirk_Business_Case/sel_Selkirk_Business_Case.php',
      'tab' => true,
    ),
    10 => 
    array (
      'module' => 'sel_Selkirk_Approvals',
      'class' => 'sel_Selkirk_Approvals',
      'path' => 'modules/sel_Selkirk_Approvals/sel_Selkirk_Approvals.php',
      'tab' => true,
    ),
    11 => 
    array (
      'module' => 'sel_Selkirk_MileStone',
      'class' => 'sel_Selkirk_MileStone',
      'path' => 'modules/sel_Selkirk_MileStone/sel_Selkirk_MileStone.php',
      'tab' => true,
    ),
    12 => 
    array (
      'module' => 'sel_Selkirk_Client',
      'class' => 'sel_Selkirk_Client',
      'path' => 'modules/sel_Selkirk_Client/sel_Selkirk_Client.php',
      'tab' => true,
    ),
    13 => 
    array (
      'module' => 'sel_Selkirk_Partner',
      'class' => 'sel_Selkirk_Partner',
      'path' => 'modules/sel_Selkirk_Partner/sel_Selkirk_Partner.php',
      'tab' => true,
    ),
    14 => 
    array (
      'module' => 'sel_Student_Project',
      'class' => 'sel_Student_Project',
      'path' => 'modules/sel_Student_Project/sel_Student_Project.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_activity_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_activity_securitygroups_sel_Selkirk_Activity.php',
      'to_module' => 'sel_Selkirk_Activity',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_service_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_service_securitygroups_sel_Selkirk_Service.php',
      'to_module' => 'sel_Selkirk_Service',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_funding_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_funding_securitygroups_sel_Selkirk_Funding.php',
      'to_module' => 'sel_Selkirk_Funding',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_template_sel_selkirk_document_sel_Selkirk_Template.php',
      'to_module' => 'sel_Selkirk_Template',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_template_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_template_securitygroups_sel_Selkirk_Template.php',
      'to_module' => 'sel_Selkirk_Template',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_contact_sel_selkirk_activity_sel_Selkirk_Contact.php',
      'to_module' => 'sel_Selkirk_Contact',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_contact_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_contact_securitygroups_sel_Selkirk_Contact.php',
      'to_module' => 'sel_Selkirk_Contact',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_student_activity_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_student_activity_securitygroups_sel_Student_Activity.php',
      'to_module' => 'sel_Student_Activity',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_team_users_Users.php',
      'to_module' => 'Users',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_team_users_sel_Selkirk_Team.php',
      'to_module' => 'sel_Selkirk_Team',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_team_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_team_securitygroups_sel_Selkirk_Team.php',
      'to_module' => 'sel_Selkirk_Team',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_document_sel_selkirk_client_sel_Selkirk_Client.php',
      'to_module' => 'sel_Selkirk_Client',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_document_sel_selkirk_client_sel_Selkirk_Document.php',
      'to_module' => 'sel_Selkirk_Document',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_document_sel_selkirk_project_sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_document_sel_selkirk_project_sel_Selkirk_Document.php',
      'to_module' => 'sel_Selkirk_Document',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_document_sel_selkirk_service_sel_Selkirk_Service.php',
      'to_module' => 'sel_Selkirk_Service',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_document_sel_selkirk_service_sel_Selkirk_Document.php',
      'to_module' => 'sel_Selkirk_Document',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_document_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    25 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_document_securitygroups_sel_Selkirk_Document.php',
      'to_module' => 'sel_Selkirk_Document',
    ),
    26 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_project_sel_selkirk_service_sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
    ),
    27 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_project_sel_selkirk_funding_sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
    ),
    28 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_project_sel_selkirk_milestone_sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
    ),
    29 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_project_sel_selkirk_partner_sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
    ),
    30 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_project_sel_selkirk_business_case_sel_Selkirk_Business_Case.php',
      'to_module' => 'sel_Selkirk_Business_Case',
    ),
    31 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_project_sel_selkirk_business_case_sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
    ),
    32 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_project_sel_selkirk_team_sel_Selkirk_Team.php',
      'to_module' => 'sel_Selkirk_Team',
    ),
    33 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_project_sel_selkirk_team_sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
    ),
    34 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_project_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    35 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_project_securitygroups_sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
    ),
    36 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_business_case_sel_selkirk_approvals_sel_Selkirk_Business_Case.php',
      'to_module' => 'sel_Selkirk_Business_Case',
    ),
    37 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_business_case_sel_selkirk_team_sel_Selkirk_Team.php',
      'to_module' => 'sel_Selkirk_Team',
    ),
    38 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_business_case_sel_selkirk_team_sel_Selkirk_Business_Case.php',
      'to_module' => 'sel_Selkirk_Business_Case',
    ),
    39 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_business_case_sel_selkirk_document_sel_Selkirk_Business_Case.php',
      'to_module' => 'sel_Selkirk_Business_Case',
    ),
    40 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_business_case_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    41 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_business_case_securitygroups_sel_Selkirk_Business_Case.php',
      'to_module' => 'sel_Selkirk_Business_Case',
    ),
    42 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_approvals_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    43 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_approvals_securitygroups_sel_Selkirk_Approvals.php',
      'to_module' => 'sel_Selkirk_Approvals',
    ),
    44 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_milestone_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    45 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_milestone_securitygroups_sel_Selkirk_MileStone.php',
      'to_module' => 'sel_Selkirk_MileStone',
    ),
    46 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_client_sel_selkirk_service_sel_Selkirk_Client.php',
      'to_module' => 'sel_Selkirk_Client',
    ),
    47 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_client_sel_selkirk_contact_sel_Selkirk_Contact.php',
      'to_module' => 'sel_Selkirk_Contact',
    ),
    48 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_client_sel_selkirk_contact_sel_Selkirk_Client.php',
      'to_module' => 'sel_Selkirk_Client',
    ),
    49 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_client_sel_selkirk_activity_sel_Selkirk_Client.php',
      'to_module' => 'sel_Selkirk_Client',
    ),
    50 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_client_sel_student_activity_sel_Selkirk_Client.php',
      'to_module' => 'sel_Selkirk_Client',
    ),
    51 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_client_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    52 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_client_securitygroups_sel_Selkirk_Client.php',
      'to_module' => 'sel_Selkirk_Client',
    ),
    53 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_partner_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    54 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_selkirk_partner_securitygroups_sel_Selkirk_Partner.php',
      'to_module' => 'sel_Selkirk_Partner',
    ),
    55 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_student_project_sel_student_activity_sel_Student_Project.php',
      'to_module' => 'sel_Student_Project',
    ),
    56 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_student_project_sel_selkirk_document_sel_Selkirk_Document.php',
      'to_module' => 'sel_Selkirk_Document',
    ),
    57 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_student_project_sel_selkirk_document_sel_Student_Project.php',
      'to_module' => 'sel_Student_Project',
    ),
    58 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_student_project_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    59 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/sel_student_project_securitygroups_sel_Student_Project.php',
      'to_module' => 'sel_Student_Project',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_selkirk_activity_securitygroupsMetaData.php',
    ),
    1 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_selkirk_service_securitygroupsMetaData.php',
    ),
    2 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_selkirk_funding_securitygroupsMetaData.php',
    ),
    3 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_selkirk_template_sel_selkirk_documentMetaData.php',
    ),
    4 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_selkirk_template_securitygroupsMetaData.php',
    ),
    5 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_selkirk_contact_sel_selkirk_activityMetaData.php',
    ),
    6 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_selkirk_contact_securitygroupsMetaData.php',
    ),
    7 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_student_activity_securitygroupsMetaData.php',
    ),
    8 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_selkirk_team_usersMetaData.php',
    ),
    9 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_selkirk_team_securitygroupsMetaData.php',
    ),
    10 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_selkirk_document_sel_selkirk_clientMetaData.php',
    ),
    11 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_selkirk_document_sel_selkirk_projectMetaData.php',
    ),
    12 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_selkirk_document_sel_selkirk_serviceMetaData.php',
    ),
    13 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_selkirk_document_securitygroupsMetaData.php',
    ),
    14 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_selkirk_project_sel_selkirk_serviceMetaData.php',
    ),
    15 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_selkirk_project_sel_selkirk_fundingMetaData.php',
    ),
    16 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_selkirk_project_sel_selkirk_milestoneMetaData.php',
    ),
    17 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_selkirk_project_sel_selkirk_partnerMetaData.php',
    ),
    18 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_selkirk_project_sel_selkirk_business_caseMetaData.php',
    ),
    19 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_selkirk_project_sel_selkirk_teamMetaData.php',
    ),
    20 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_selkirk_project_securitygroupsMetaData.php',
    ),
    21 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_selkirk_business_case_sel_selkirk_approvalsMetaData.php',
    ),
    22 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_selkirk_business_case_sel_selkirk_teamMetaData.php',
    ),
    23 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_selkirk_business_case_sel_selkirk_documentMetaData.php',
    ),
    24 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_selkirk_business_case_securitygroupsMetaData.php',
    ),
    25 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_selkirk_approvals_securitygroupsMetaData.php',
    ),
    26 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_selkirk_milestone_securitygroupsMetaData.php',
    ),
    27 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_selkirk_client_sel_selkirk_serviceMetaData.php',
    ),
    28 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_selkirk_client_sel_selkirk_contactMetaData.php',
    ),
    29 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_selkirk_client_sel_selkirk_activityMetaData.php',
    ),
    30 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_selkirk_client_sel_student_activityMetaData.php',
    ),
    31 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_selkirk_client_securitygroupsMetaData.php',
    ),
    32 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_selkirk_partner_securitygroupsMetaData.php',
    ),
    33 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_student_project_sel_student_activityMetaData.php',
    ),
    34 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_student_project_sel_selkirk_documentMetaData.php',
    ),
    35 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/sel_student_project_securitygroupsMetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/sel_Selkirk_Activity',
      'to' => 'modules/sel_Selkirk_Activity',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/sel_Selkirk_Service',
      'to' => 'modules/sel_Selkirk_Service',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/sel_Selkirk_Funding',
      'to' => 'modules/sel_Selkirk_Funding',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/sel_Selkirk_Template',
      'to' => 'modules/sel_Selkirk_Template',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/sel_Selkirk_Contact',
      'to' => 'modules/sel_Selkirk_Contact',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/sel_Student_Activity',
      'to' => 'modules/sel_Student_Activity',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/modules/sel_Selkirk_Team',
      'to' => 'modules/sel_Selkirk_Team',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/modules/sel_Selkirk_Document',
      'to' => 'modules/sel_Selkirk_Document',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/modules/sel_Selkirk_Project',
      'to' => 'modules/sel_Selkirk_Project',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/modules/sel_Selkirk_Business_Case',
      'to' => 'modules/sel_Selkirk_Business_Case',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/modules/sel_Selkirk_Approvals',
      'to' => 'modules/sel_Selkirk_Approvals',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/modules/sel_Selkirk_MileStone',
      'to' => 'modules/sel_Selkirk_MileStone',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/modules/sel_Selkirk_Client',
      'to' => 'modules/sel_Selkirk_Client',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/modules/sel_Selkirk_Partner',
      'to' => 'modules/sel_Selkirk_Partner',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/modules/sel_Student_Project',
      'to' => 'modules/sel_Student_Project',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'es_es',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'ru_ru',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Activity.php',
      'to_module' => 'sel_Selkirk_Activity',
      'language' => 'en_us',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Activity.php',
      'to_module' => 'sel_Selkirk_Activity',
      'language' => 'es_es',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Activity.php',
      'to_module' => 'sel_Selkirk_Activity',
      'language' => 'ru_ru',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'en_us',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'es_es',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'ru_ru',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Service.php',
      'to_module' => 'sel_Selkirk_Service',
      'language' => 'en_us',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Service.php',
      'to_module' => 'sel_Selkirk_Service',
      'language' => 'es_es',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Service.php',
      'to_module' => 'sel_Selkirk_Service',
      'language' => 'ru_ru',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'en_us',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'es_es',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'ru_ru',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Funding.php',
      'to_module' => 'sel_Selkirk_Funding',
      'language' => 'en_us',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Funding.php',
      'to_module' => 'sel_Selkirk_Funding',
      'language' => 'es_es',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Funding.php',
      'to_module' => 'sel_Selkirk_Funding',
      'language' => 'ru_ru',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Document.php',
      'to_module' => 'sel_Selkirk_Document',
      'language' => 'en_us',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Document.php',
      'to_module' => 'sel_Selkirk_Document',
      'language' => 'es_es',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Document.php',
      'to_module' => 'sel_Selkirk_Document',
      'language' => 'ru_ru',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Template.php',
      'to_module' => 'sel_Selkirk_Template',
      'language' => 'en_us',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Template.php',
      'to_module' => 'sel_Selkirk_Template',
      'language' => 'es_es',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Template.php',
      'to_module' => 'sel_Selkirk_Template',
      'language' => 'ru_ru',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'en_us',
    ),
    25 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'es_es',
    ),
    26 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'ru_ru',
    ),
    27 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Template.php',
      'to_module' => 'sel_Selkirk_Template',
      'language' => 'en_us',
    ),
    28 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Template.php',
      'to_module' => 'sel_Selkirk_Template',
      'language' => 'es_es',
    ),
    29 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Template.php',
      'to_module' => 'sel_Selkirk_Template',
      'language' => 'ru_ru',
    ),
    30 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Activity.php',
      'to_module' => 'sel_Selkirk_Activity',
      'language' => 'en_us',
    ),
    31 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Activity.php',
      'to_module' => 'sel_Selkirk_Activity',
      'language' => 'es_es',
    ),
    32 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Activity.php',
      'to_module' => 'sel_Selkirk_Activity',
      'language' => 'ru_ru',
    ),
    33 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Contact.php',
      'to_module' => 'sel_Selkirk_Contact',
      'language' => 'en_us',
    ),
    34 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Contact.php',
      'to_module' => 'sel_Selkirk_Contact',
      'language' => 'es_es',
    ),
    35 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Contact.php',
      'to_module' => 'sel_Selkirk_Contact',
      'language' => 'ru_ru',
    ),
    36 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'en_us',
    ),
    37 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'es_es',
    ),
    38 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'ru_ru',
    ),
    39 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Contact.php',
      'to_module' => 'sel_Selkirk_Contact',
      'language' => 'en_us',
    ),
    40 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Contact.php',
      'to_module' => 'sel_Selkirk_Contact',
      'language' => 'es_es',
    ),
    41 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Contact.php',
      'to_module' => 'sel_Selkirk_Contact',
      'language' => 'ru_ru',
    ),
    42 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'en_us',
    ),
    43 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'es_es',
    ),
    44 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'ru_ru',
    ),
    45 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Student_Activity.php',
      'to_module' => 'sel_Student_Activity',
      'language' => 'en_us',
    ),
    46 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Student_Activity.php',
      'to_module' => 'sel_Student_Activity',
      'language' => 'es_es',
    ),
    47 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Student_Activity.php',
      'to_module' => 'sel_Student_Activity',
      'language' => 'ru_ru',
    ),
    48 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'en_us',
    ),
    49 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'es_es',
    ),
    50 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'ru_ru',
    ),
    51 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Team.php',
      'to_module' => 'sel_Selkirk_Team',
      'language' => 'en_us',
    ),
    52 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Team.php',
      'to_module' => 'sel_Selkirk_Team',
      'language' => 'es_es',
    ),
    53 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Team.php',
      'to_module' => 'sel_Selkirk_Team',
      'language' => 'ru_ru',
    ),
    54 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'en_us',
    ),
    55 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'es_es',
    ),
    56 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'ru_ru',
    ),
    57 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Team.php',
      'to_module' => 'sel_Selkirk_Team',
      'language' => 'en_us',
    ),
    58 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Team.php',
      'to_module' => 'sel_Selkirk_Team',
      'language' => 'es_es',
    ),
    59 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Team.php',
      'to_module' => 'sel_Selkirk_Team',
      'language' => 'ru_ru',
    ),
    60 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Client.php',
      'to_module' => 'sel_Selkirk_Client',
      'language' => 'en_us',
    ),
    61 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Client.php',
      'to_module' => 'sel_Selkirk_Client',
      'language' => 'es_es',
    ),
    62 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Client.php',
      'to_module' => 'sel_Selkirk_Client',
      'language' => 'ru_ru',
    ),
    63 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Document.php',
      'to_module' => 'sel_Selkirk_Document',
      'language' => 'en_us',
    ),
    64 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Document.php',
      'to_module' => 'sel_Selkirk_Document',
      'language' => 'es_es',
    ),
    65 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Document.php',
      'to_module' => 'sel_Selkirk_Document',
      'language' => 'ru_ru',
    ),
    66 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
      'language' => 'en_us',
    ),
    67 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
      'language' => 'es_es',
    ),
    68 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
      'language' => 'ru_ru',
    ),
    69 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Document.php',
      'to_module' => 'sel_Selkirk_Document',
      'language' => 'en_us',
    ),
    70 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Document.php',
      'to_module' => 'sel_Selkirk_Document',
      'language' => 'es_es',
    ),
    71 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Document.php',
      'to_module' => 'sel_Selkirk_Document',
      'language' => 'ru_ru',
    ),
    72 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Service.php',
      'to_module' => 'sel_Selkirk_Service',
      'language' => 'en_us',
    ),
    73 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Service.php',
      'to_module' => 'sel_Selkirk_Service',
      'language' => 'es_es',
    ),
    74 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Service.php',
      'to_module' => 'sel_Selkirk_Service',
      'language' => 'ru_ru',
    ),
    75 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Document.php',
      'to_module' => 'sel_Selkirk_Document',
      'language' => 'en_us',
    ),
    76 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Document.php',
      'to_module' => 'sel_Selkirk_Document',
      'language' => 'es_es',
    ),
    77 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Document.php',
      'to_module' => 'sel_Selkirk_Document',
      'language' => 'ru_ru',
    ),
    78 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'en_us',
    ),
    79 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'es_es',
    ),
    80 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'ru_ru',
    ),
    81 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Document.php',
      'to_module' => 'sel_Selkirk_Document',
      'language' => 'en_us',
    ),
    82 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Document.php',
      'to_module' => 'sel_Selkirk_Document',
      'language' => 'es_es',
    ),
    83 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Document.php',
      'to_module' => 'sel_Selkirk_Document',
      'language' => 'ru_ru',
    ),
    84 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Service.php',
      'to_module' => 'sel_Selkirk_Service',
      'language' => 'en_us',
    ),
    85 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Service.php',
      'to_module' => 'sel_Selkirk_Service',
      'language' => 'es_es',
    ),
    86 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Service.php',
      'to_module' => 'sel_Selkirk_Service',
      'language' => 'ru_ru',
    ),
    87 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
      'language' => 'en_us',
    ),
    88 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
      'language' => 'es_es',
    ),
    89 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
      'language' => 'ru_ru',
    ),
    90 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Funding.php',
      'to_module' => 'sel_Selkirk_Funding',
      'language' => 'en_us',
    ),
    91 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Funding.php',
      'to_module' => 'sel_Selkirk_Funding',
      'language' => 'es_es',
    ),
    92 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Funding.php',
      'to_module' => 'sel_Selkirk_Funding',
      'language' => 'ru_ru',
    ),
    93 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
      'language' => 'en_us',
    ),
    94 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
      'language' => 'es_es',
    ),
    95 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
      'language' => 'ru_ru',
    ),
    96 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_MileStone.php',
      'to_module' => 'sel_Selkirk_MileStone',
      'language' => 'en_us',
    ),
    97 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_MileStone.php',
      'to_module' => 'sel_Selkirk_MileStone',
      'language' => 'es_es',
    ),
    98 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_MileStone.php',
      'to_module' => 'sel_Selkirk_MileStone',
      'language' => 'ru_ru',
    ),
    99 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
      'language' => 'en_us',
    ),
    100 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
      'language' => 'es_es',
    ),
    101 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
      'language' => 'ru_ru',
    ),
    102 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Partner.php',
      'to_module' => 'sel_Selkirk_Partner',
      'language' => 'en_us',
    ),
    103 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Partner.php',
      'to_module' => 'sel_Selkirk_Partner',
      'language' => 'es_es',
    ),
    104 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Partner.php',
      'to_module' => 'sel_Selkirk_Partner',
      'language' => 'ru_ru',
    ),
    105 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
      'language' => 'en_us',
    ),
    106 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
      'language' => 'es_es',
    ),
    107 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
      'language' => 'ru_ru',
    ),
    108 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Business_Case.php',
      'to_module' => 'sel_Selkirk_Business_Case',
      'language' => 'en_us',
    ),
    109 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Business_Case.php',
      'to_module' => 'sel_Selkirk_Business_Case',
      'language' => 'es_es',
    ),
    110 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Business_Case.php',
      'to_module' => 'sel_Selkirk_Business_Case',
      'language' => 'ru_ru',
    ),
    111 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
      'language' => 'en_us',
    ),
    112 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
      'language' => 'es_es',
    ),
    113 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
      'language' => 'ru_ru',
    ),
    114 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Team.php',
      'to_module' => 'sel_Selkirk_Team',
      'language' => 'en_us',
    ),
    115 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Team.php',
      'to_module' => 'sel_Selkirk_Team',
      'language' => 'es_es',
    ),
    116 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Team.php',
      'to_module' => 'sel_Selkirk_Team',
      'language' => 'ru_ru',
    ),
    117 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
      'language' => 'en_us',
    ),
    118 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
      'language' => 'es_es',
    ),
    119 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
      'language' => 'ru_ru',
    ),
    120 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'en_us',
    ),
    121 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'es_es',
    ),
    122 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'ru_ru',
    ),
    123 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
      'language' => 'en_us',
    ),
    124 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
      'language' => 'es_es',
    ),
    125 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
      'language' => 'ru_ru',
    ),
    126 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Approvals.php',
      'to_module' => 'sel_Selkirk_Approvals',
      'language' => 'en_us',
    ),
    127 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Approvals.php',
      'to_module' => 'sel_Selkirk_Approvals',
      'language' => 'es_es',
    ),
    128 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Approvals.php',
      'to_module' => 'sel_Selkirk_Approvals',
      'language' => 'ru_ru',
    ),
    129 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Business_Case.php',
      'to_module' => 'sel_Selkirk_Business_Case',
      'language' => 'en_us',
    ),
    130 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Business_Case.php',
      'to_module' => 'sel_Selkirk_Business_Case',
      'language' => 'es_es',
    ),
    131 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Business_Case.php',
      'to_module' => 'sel_Selkirk_Business_Case',
      'language' => 'ru_ru',
    ),
    132 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Team.php',
      'to_module' => 'sel_Selkirk_Team',
      'language' => 'en_us',
    ),
    133 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Team.php',
      'to_module' => 'sel_Selkirk_Team',
      'language' => 'es_es',
    ),
    134 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Team.php',
      'to_module' => 'sel_Selkirk_Team',
      'language' => 'ru_ru',
    ),
    135 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Business_Case.php',
      'to_module' => 'sel_Selkirk_Business_Case',
      'language' => 'en_us',
    ),
    136 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Business_Case.php',
      'to_module' => 'sel_Selkirk_Business_Case',
      'language' => 'es_es',
    ),
    137 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Business_Case.php',
      'to_module' => 'sel_Selkirk_Business_Case',
      'language' => 'ru_ru',
    ),
    138 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Document.php',
      'to_module' => 'sel_Selkirk_Document',
      'language' => 'en_us',
    ),
    139 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Document.php',
      'to_module' => 'sel_Selkirk_Document',
      'language' => 'es_es',
    ),
    140 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Document.php',
      'to_module' => 'sel_Selkirk_Document',
      'language' => 'ru_ru',
    ),
    141 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Business_Case.php',
      'to_module' => 'sel_Selkirk_Business_Case',
      'language' => 'en_us',
    ),
    142 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Business_Case.php',
      'to_module' => 'sel_Selkirk_Business_Case',
      'language' => 'es_es',
    ),
    143 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Business_Case.php',
      'to_module' => 'sel_Selkirk_Business_Case',
      'language' => 'ru_ru',
    ),
    144 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'en_us',
    ),
    145 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'es_es',
    ),
    146 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'ru_ru',
    ),
    147 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Business_Case.php',
      'to_module' => 'sel_Selkirk_Business_Case',
      'language' => 'en_us',
    ),
    148 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Business_Case.php',
      'to_module' => 'sel_Selkirk_Business_Case',
      'language' => 'es_es',
    ),
    149 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Business_Case.php',
      'to_module' => 'sel_Selkirk_Business_Case',
      'language' => 'ru_ru',
    ),
    150 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'en_us',
    ),
    151 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'es_es',
    ),
    152 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'ru_ru',
    ),
    153 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Approvals.php',
      'to_module' => 'sel_Selkirk_Approvals',
      'language' => 'en_us',
    ),
    154 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Approvals.php',
      'to_module' => 'sel_Selkirk_Approvals',
      'language' => 'es_es',
    ),
    155 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Approvals.php',
      'to_module' => 'sel_Selkirk_Approvals',
      'language' => 'ru_ru',
    ),
    156 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'en_us',
    ),
    157 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'es_es',
    ),
    158 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'ru_ru',
    ),
    159 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_MileStone.php',
      'to_module' => 'sel_Selkirk_MileStone',
      'language' => 'en_us',
    ),
    160 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_MileStone.php',
      'to_module' => 'sel_Selkirk_MileStone',
      'language' => 'es_es',
    ),
    161 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_MileStone.php',
      'to_module' => 'sel_Selkirk_MileStone',
      'language' => 'ru_ru',
    ),
    162 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Service.php',
      'to_module' => 'sel_Selkirk_Service',
      'language' => 'en_us',
    ),
    163 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Service.php',
      'to_module' => 'sel_Selkirk_Service',
      'language' => 'es_es',
    ),
    164 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Service.php',
      'to_module' => 'sel_Selkirk_Service',
      'language' => 'ru_ru',
    ),
    165 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Client.php',
      'to_module' => 'sel_Selkirk_Client',
      'language' => 'en_us',
    ),
    166 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Client.php',
      'to_module' => 'sel_Selkirk_Client',
      'language' => 'es_es',
    ),
    167 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Client.php',
      'to_module' => 'sel_Selkirk_Client',
      'language' => 'ru_ru',
    ),
    168 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Contact.php',
      'to_module' => 'sel_Selkirk_Contact',
      'language' => 'en_us',
    ),
    169 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Contact.php',
      'to_module' => 'sel_Selkirk_Contact',
      'language' => 'es_es',
    ),
    170 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Contact.php',
      'to_module' => 'sel_Selkirk_Contact',
      'language' => 'ru_ru',
    ),
    171 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Client.php',
      'to_module' => 'sel_Selkirk_Client',
      'language' => 'en_us',
    ),
    172 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Client.php',
      'to_module' => 'sel_Selkirk_Client',
      'language' => 'es_es',
    ),
    173 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Client.php',
      'to_module' => 'sel_Selkirk_Client',
      'language' => 'ru_ru',
    ),
    174 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Activity.php',
      'to_module' => 'sel_Selkirk_Activity',
      'language' => 'en_us',
    ),
    175 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Activity.php',
      'to_module' => 'sel_Selkirk_Activity',
      'language' => 'es_es',
    ),
    176 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Activity.php',
      'to_module' => 'sel_Selkirk_Activity',
      'language' => 'ru_ru',
    ),
    177 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Client.php',
      'to_module' => 'sel_Selkirk_Client',
      'language' => 'en_us',
    ),
    178 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Client.php',
      'to_module' => 'sel_Selkirk_Client',
      'language' => 'es_es',
    ),
    179 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Client.php',
      'to_module' => 'sel_Selkirk_Client',
      'language' => 'ru_ru',
    ),
    180 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Student_Activity.php',
      'to_module' => 'sel_Student_Activity',
      'language' => 'en_us',
    ),
    181 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Student_Activity.php',
      'to_module' => 'sel_Student_Activity',
      'language' => 'es_es',
    ),
    182 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Student_Activity.php',
      'to_module' => 'sel_Student_Activity',
      'language' => 'ru_ru',
    ),
    183 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Client.php',
      'to_module' => 'sel_Selkirk_Client',
      'language' => 'en_us',
    ),
    184 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Client.php',
      'to_module' => 'sel_Selkirk_Client',
      'language' => 'es_es',
    ),
    185 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Client.php',
      'to_module' => 'sel_Selkirk_Client',
      'language' => 'ru_ru',
    ),
    186 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'en_us',
    ),
    187 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'es_es',
    ),
    188 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'ru_ru',
    ),
    189 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Client.php',
      'to_module' => 'sel_Selkirk_Client',
      'language' => 'en_us',
    ),
    190 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Client.php',
      'to_module' => 'sel_Selkirk_Client',
      'language' => 'es_es',
    ),
    191 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Client.php',
      'to_module' => 'sel_Selkirk_Client',
      'language' => 'ru_ru',
    ),
    192 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'en_us',
    ),
    193 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'es_es',
    ),
    194 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'ru_ru',
    ),
    195 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Partner.php',
      'to_module' => 'sel_Selkirk_Partner',
      'language' => 'en_us',
    ),
    196 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Partner.php',
      'to_module' => 'sel_Selkirk_Partner',
      'language' => 'es_es',
    ),
    197 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Partner.php',
      'to_module' => 'sel_Selkirk_Partner',
      'language' => 'ru_ru',
    ),
    198 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Student_Activity.php',
      'to_module' => 'sel_Student_Activity',
      'language' => 'en_us',
    ),
    199 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Student_Activity.php',
      'to_module' => 'sel_Student_Activity',
      'language' => 'es_es',
    ),
    200 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Student_Activity.php',
      'to_module' => 'sel_Student_Activity',
      'language' => 'ru_ru',
    ),
    201 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Student_Project.php',
      'to_module' => 'sel_Student_Project',
      'language' => 'en_us',
    ),
    202 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Student_Project.php',
      'to_module' => 'sel_Student_Project',
      'language' => 'es_es',
    ),
    203 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Student_Project.php',
      'to_module' => 'sel_Student_Project',
      'language' => 'ru_ru',
    ),
    204 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Document.php',
      'to_module' => 'sel_Selkirk_Document',
      'language' => 'en_us',
    ),
    205 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Document.php',
      'to_module' => 'sel_Selkirk_Document',
      'language' => 'es_es',
    ),
    206 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Selkirk_Document.php',
      'to_module' => 'sel_Selkirk_Document',
      'language' => 'ru_ru',
    ),
    207 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Student_Project.php',
      'to_module' => 'sel_Student_Project',
      'language' => 'en_us',
    ),
    208 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Student_Project.php',
      'to_module' => 'sel_Student_Project',
      'language' => 'es_es',
    ),
    209 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Student_Project.php',
      'to_module' => 'sel_Student_Project',
      'language' => 'ru_ru',
    ),
    210 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'en_us',
    ),
    211 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'es_es',
    ),
    212 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'ru_ru',
    ),
    213 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Student_Project.php',
      'to_module' => 'sel_Student_Project',
      'language' => 'en_us',
    ),
    214 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Student_Project.php',
      'to_module' => 'sel_Student_Project',
      'language' => 'es_es',
    ),
    215 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/sel_Student_Project.php',
      'to_module' => 'sel_Student_Project',
      'language' => 'ru_ru',
    ),
    216 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/ru_ru.lang.php',
      'to_module' => 'application',
      'language' => 'ru_ru',
    ),
    217 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    218 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/es_es.lang.php',
      'to_module' => 'application',
      'language' => 'es_es',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_activity_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_activity_securitygroups_sel_Selkirk_Activity.php',
      'to_module' => 'sel_Selkirk_Activity',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_service_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_service_securitygroups_sel_Selkirk_Service.php',
      'to_module' => 'sel_Selkirk_Service',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_funding_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_funding_securitygroups_sel_Selkirk_Funding.php',
      'to_module' => 'sel_Selkirk_Funding',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_template_sel_selkirk_document_sel_Selkirk_Document.php',
      'to_module' => 'sel_Selkirk_Document',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_template_sel_selkirk_document_sel_Selkirk_Template.php',
      'to_module' => 'sel_Selkirk_Template',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_template_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_template_securitygroups_sel_Selkirk_Template.php',
      'to_module' => 'sel_Selkirk_Template',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_contact_sel_selkirk_activity_sel_Selkirk_Activity.php',
      'to_module' => 'sel_Selkirk_Activity',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_contact_sel_selkirk_activity_sel_Selkirk_Contact.php',
      'to_module' => 'sel_Selkirk_Contact',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_contact_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_contact_securitygroups_sel_Selkirk_Contact.php',
      'to_module' => 'sel_Selkirk_Contact',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_student_activity_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_student_activity_securitygroups_sel_Student_Activity.php',
      'to_module' => 'sel_Student_Activity',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_team_users_Users.php',
      'to_module' => 'Users',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_team_users_sel_Selkirk_Team.php',
      'to_module' => 'sel_Selkirk_Team',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_team_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_team_securitygroups_sel_Selkirk_Team.php',
      'to_module' => 'sel_Selkirk_Team',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_document_sel_selkirk_client_sel_Selkirk_Client.php',
      'to_module' => 'sel_Selkirk_Client',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_document_sel_selkirk_client_sel_Selkirk_Document.php',
      'to_module' => 'sel_Selkirk_Document',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_document_sel_selkirk_project_sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_document_sel_selkirk_project_sel_Selkirk_Document.php',
      'to_module' => 'sel_Selkirk_Document',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_document_sel_selkirk_service_sel_Selkirk_Service.php',
      'to_module' => 'sel_Selkirk_Service',
    ),
    25 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_document_sel_selkirk_service_sel_Selkirk_Document.php',
      'to_module' => 'sel_Selkirk_Document',
    ),
    26 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_document_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    27 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_document_securitygroups_sel_Selkirk_Document.php',
      'to_module' => 'sel_Selkirk_Document',
    ),
    28 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_project_sel_selkirk_service_sel_Selkirk_Service.php',
      'to_module' => 'sel_Selkirk_Service',
    ),
    29 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_project_sel_selkirk_service_sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
    ),
    30 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_project_sel_selkirk_funding_sel_Selkirk_Funding.php',
      'to_module' => 'sel_Selkirk_Funding',
    ),
    31 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_project_sel_selkirk_funding_sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
    ),
    32 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_project_sel_selkirk_milestone_sel_Selkirk_MileStone.php',
      'to_module' => 'sel_Selkirk_MileStone',
    ),
    33 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_project_sel_selkirk_milestone_sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
    ),
    34 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_project_sel_selkirk_partner_sel_Selkirk_Partner.php',
      'to_module' => 'sel_Selkirk_Partner',
    ),
    35 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_project_sel_selkirk_partner_sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
    ),
    36 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_project_sel_selkirk_business_case_sel_Selkirk_Business_Case.php',
      'to_module' => 'sel_Selkirk_Business_Case',
    ),
    37 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_project_sel_selkirk_business_case_sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
    ),
    38 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_project_sel_selkirk_team_sel_Selkirk_Team.php',
      'to_module' => 'sel_Selkirk_Team',
    ),
    39 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_project_sel_selkirk_team_sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
    ),
    40 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_project_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    41 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_project_securitygroups_sel_Selkirk_Project.php',
      'to_module' => 'sel_Selkirk_Project',
    ),
    42 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_business_case_sel_selkirk_approvals_sel_Selkirk_Approvals.php',
      'to_module' => 'sel_Selkirk_Approvals',
    ),
    43 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_business_case_sel_selkirk_approvals_sel_Selkirk_Business_Case.php',
      'to_module' => 'sel_Selkirk_Business_Case',
    ),
    44 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_business_case_sel_selkirk_team_sel_Selkirk_Team.php',
      'to_module' => 'sel_Selkirk_Team',
    ),
    45 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_business_case_sel_selkirk_team_sel_Selkirk_Business_Case.php',
      'to_module' => 'sel_Selkirk_Business_Case',
    ),
    46 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_business_case_sel_selkirk_document_sel_Selkirk_Document.php',
      'to_module' => 'sel_Selkirk_Document',
    ),
    47 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_business_case_sel_selkirk_document_sel_Selkirk_Business_Case.php',
      'to_module' => 'sel_Selkirk_Business_Case',
    ),
    48 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_business_case_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    49 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_business_case_securitygroups_sel_Selkirk_Business_Case.php',
      'to_module' => 'sel_Selkirk_Business_Case',
    ),
    50 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_approvals_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    51 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_approvals_securitygroups_sel_Selkirk_Approvals.php',
      'to_module' => 'sel_Selkirk_Approvals',
    ),
    52 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_milestone_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    53 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_milestone_securitygroups_sel_Selkirk_MileStone.php',
      'to_module' => 'sel_Selkirk_MileStone',
    ),
    54 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_client_sel_selkirk_service_sel_Selkirk_Service.php',
      'to_module' => 'sel_Selkirk_Service',
    ),
    55 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_client_sel_selkirk_service_sel_Selkirk_Client.php',
      'to_module' => 'sel_Selkirk_Client',
    ),
    56 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_client_sel_selkirk_contact_sel_Selkirk_Contact.php',
      'to_module' => 'sel_Selkirk_Contact',
    ),
    57 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_client_sel_selkirk_contact_sel_Selkirk_Client.php',
      'to_module' => 'sel_Selkirk_Client',
    ),
    58 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_client_sel_selkirk_activity_sel_Selkirk_Activity.php',
      'to_module' => 'sel_Selkirk_Activity',
    ),
    59 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_client_sel_selkirk_activity_sel_Selkirk_Client.php',
      'to_module' => 'sel_Selkirk_Client',
    ),
    60 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_client_sel_student_activity_sel_Student_Activity.php',
      'to_module' => 'sel_Student_Activity',
    ),
    61 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_client_sel_student_activity_sel_Selkirk_Client.php',
      'to_module' => 'sel_Selkirk_Client',
    ),
    62 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_client_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    63 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_client_securitygroups_sel_Selkirk_Client.php',
      'to_module' => 'sel_Selkirk_Client',
    ),
    64 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_partner_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    65 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_selkirk_partner_securitygroups_sel_Selkirk_Partner.php',
      'to_module' => 'sel_Selkirk_Partner',
    ),
    66 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_student_project_sel_student_activity_sel_Student_Activity.php',
      'to_module' => 'sel_Student_Activity',
    ),
    67 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_student_project_sel_student_activity_sel_Student_Project.php',
      'to_module' => 'sel_Student_Project',
    ),
    68 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_student_project_sel_selkirk_document_sel_Selkirk_Document.php',
      'to_module' => 'sel_Selkirk_Document',
    ),
    69 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_student_project_sel_selkirk_document_sel_Student_Project.php',
      'to_module' => 'sel_Student_Project',
    ),
    70 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_student_project_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    71 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/sel_student_project_securitygroups_sel_Student_Project.php',
      'to_module' => 'sel_Student_Project',
    ),
  ),
  'layoutfields' => 
  array (
    0 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    1 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    2 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    3 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    4 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    5 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    6 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    7 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    8 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    9 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    10 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    11 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
  ),
);